(in-package :mu-cl-resources)

(add-prefix "trans" "http://translation.escoportal.eu/vocab/")
(add-prefix "dcterms" "http://purl.org/dc/terms/")
(add-prefix "foaf" "http://xmlns.com/foaf/0.1/")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "skosxl" "http://www.w3.org/2008/05/skos-xl#")
(add-prefix "esco" "http://data.europa.eu/esco/model#")
(add-prefix "account" "http://mu.semte.ch/vocabularies/account/")
(add-prefix "hier" "http://mu.semte.ch/vocabularies/hierarchy/")
(add-prefix "etms" "http://sem.tenforce.com/vocabularies/etms/")
(add-prefix "ext" "http://mu.semte.ch/vocabularies/ext/")